# Generated by Django 2.2.4 on 2019-08-08 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unassigned', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='unassigned', max_length=100)),
                ('location', models.CharField(default='unassigned', max_length=100)),
                ('single_serve', models.BooleanField(default=True)),
                ('tasting_note', models.TextField(default='unassigned')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unassigned', max_length=100)),
                ('ingredients_list', models.TextField(default='unassigned', max_length=1000)),
                ('preperation', models.TextField(default='unassigned', max_length=1000)),
                ('location', models.CharField(default='unassigned', max_length=100)),
                ('category', models.TextField(default='unassigned', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unassigned', max_length=100)),
                ('open_date_time', models.DateTimeField(auto_now_add=True)),
                ('close_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unassigned', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='barapp.Ingredient')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='barapp.Tab')),
            ],
        ),
    ]
