# Generated by Django 2.2.4 on 2019-08-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='drinks',
            field=models.ManyToManyField(blank=True, null=True, to='barapp.Drink'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='barapp.Ingredient'),
        ),
    ]
