# Generated by Django 2.2.4 on 2019-08-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='close_date_time',
            field=models.DateTimeField(),
        ),
    ]
