# Generated by Django 2.2.4 on 2019-08-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='location',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='tasting_note',
            field=models.TextField(default='unassigned'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.TextField(default='unassigned', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_list',
            field=models.TextField(default='unassigned', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='location',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preperation',
            field=models.TextField(default='unassigned', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tab',
            name='name',
            field=models.CharField(default='unassigned', max_length=100),
        ),
    ]
