# Generated by Django 2.2.4 on 2019-08-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0002_auto_20190809_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='close_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
