# Generated by Django 2.2.4 on 2019-08-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0004_auto_20190809_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ManyToManyField(to='barapp.Category'),
        ),
    ]
