# Generated by Django 2.2.4 on 2019-08-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0005_auto_20190809_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(default='unassigned', max_length=100),
        ),
    ]
